### ISSUE TITLE
Problems uploading certain types of PDFs and PPTs to documents/libraries plugin

### ISSUE THREAD

**Issue by SuperGlobal** [SocialEngine/phpv4-issues#19]
When uploading certain PDFs and PPTs, the documents plugin hangs when 'conversion is in progress' and does not complete. I also see errors showing up in the error log pertaining to the decode.php which I am presuming is part of the conversion process. Here is the trace:

2015-03-06T13:13:14+00:00 CRIT (2): exception 'Zend_Json_Exception' with message 'Must specify JSON encoded source for decoding' in /home/profology/public_html/beta/application/libraries/Zend/Json/Decoder.php:148
Stack trace:
#0 /home/profology/public_html/beta/application/modules/Sitestaticpage/widgets/html-blocks/Controller.php(35): Zend_Json_Decoder::decode(NULL)
#1 /home/profology/public_html/beta/application/libraries/Engine/Content/Widget/Abstract.php(254): Sitestaticpage_Widget_HtmlBlocksController->indexAction()
#2 /home/profology/public_html/beta/application/libraries/Engine/Content/Element/Widget.php(73): Engine_Content_Widget_Abstract->render(NULL)
#3 /home/profology/public_html/beta/application/libraries/Engine/Content/Element/Abstract.php(583): Engine_Content_Element_Widget->_render()
#4 /home/profology/public_html/beta/application/libraries/Engine/Content/Decorator/Children.php(31): Engine_Content_Element_Abstract->render()
#5 /home/profology/public_html/beta/application/libraries/Engine/Content/Element/Abstract.php(594): Engine_Content_Decorator_Children->render('')
#6 /home/profology/public_html/beta/application/libraries/Engine/Content/Decorator/Children.php(31): Engine_Content_Element_Abstract->render()
#7 /home/profology/public_html/beta/application/libraries/Engine/Content/Element/Abstract.php(594): Engine_Content_Decorator_Children->render('')
#8 /home/profology/public_html/beta/application/libraries/Engine/Content/Decorator/Children.php(31): Engine_Content_Element_Abstract->render()
#9 /home/profology/public_html/beta/application/libraries/Engine/Content/Element/Abstract.php(594): Engine_Content_Decorator_Children->render('')
#10 /home/profology/public_html/beta/application/libraries/Engine/Content.php(208): Engine_Content_Element_Abstract->render()
#11 /home/profology/public_html/beta/application/libraries/Engine/Content/Controller/Action/Helper/Content.php(136): Engine_Content->render('user_index_home')
#12 /home/profology/public_html/beta/application/libraries/Engine/Content/Controller/Action/Helper/Content.php(38): Engine_Content_Controller_Action_Helper_Content->render()
#13 /home/profology/public_html/beta/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Engine_Content_Controller_Action_Helper_Content->postDispatch()
#14 /home/profology/public_html/beta/application/libraries/Zend/Controller/Action.php(523): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#15 /home/profology/public_html/beta/application/libraries/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action->dispatch('homeAction')
#16 /home/profology/public_html/beta/application/libraries/Zend/Controller/Front.php(946): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#17 /home/profology/public_html/beta/application/modules/Core/Bootstrap.php(80): Zend_Controller_Front->dispatch()
#18 /home/profology/public_html/beta/application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
#19 /home/profology/public_html/beta/application/index.php(205): Engine_Application->run()
#20 /home/profology/public_html/beta/index.php(24): include('/home/profology...')
#21 {main}

**Comment by SuperGlobal** [comment]
Apparently this is a plugin not written by SocialEngine, I will have to contact the third-party to get this resolved.
