### ISSUE TITLE
Zend DB Error in admin/core/settings/general/ when updating settings.

### ISSUE THREAD

**Issue by crazytechjunkie** [SocialEngine/phpv4-issues#442]
What are the steps to reproduce this issue?
-------------------------------------------
1. Login into Admin Area
2. Navigate to General Settings... update any setting and press "Save Changes"
3. Settings are not saved and the following error shows.

What happens is this error is displayed after clicking "Save Changes"...

What were you expecting to happen?
----------------------------------
I was expecting to have changes saved. I have installed on two different with two different domain names and still get the same error when updating "General Settings" area in Admin Panel.

Error Log:
----------------------------
```
We are currently experiencing some technical issues. Please try again or report this to your site administrator using the contact form.

Administrator: Please check the error log in your admin panel for more information regarding this error.

Error Code: 86409a

exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Column 'value' cannot be null' in /home/mysite/public_html/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /home/mysite/public_html/application/libraries/Zend/Db/Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /home/mysite/public_html/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /home/mysite/public_html/application/libraries/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `en...', Array)
#3 /home/mysite/public_html/application/libraries/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('engine4_core_se...', Array)
#4 /home/mysite/public_html/application/libraries/Engine/Db/Table.php(149): Zend_Db_Table_Abstract->insert(Array)
#5 /home/mysite/public_html/application/modules/Core/Model/DbTable/Settings.php(156): Engine_Db_Table->insert(Array)
#6 /home/mysite/public_html/application/modules/Core/Model/DbTable/Settings.php(109): Core_Model_DbTable_Settings->setSetting('core.general.si...', NULL)
#7 /home/mysite/public_html/application/modules/Core/Api/Settings.php(35): Core_Model_DbTable_Settings->setSetting('core_general', Array)
#8 /home/mysite/public_html/application/modules/Core/controllers/AdminSettingsController.php(68): Core_Api_Settings->__set('core_general', Array)
#9 /home/mysite/public_html/application/libraries/Zend/Controller/Action.php(516): Core_AdminSettingsController->generalAction()
#10 /home/mysite/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('generalAction')
#11 /home/mysite/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /home/mysite/public_html/application/modules/Core/Bootstrap.php(84): Zend_Controller_Front->dispatch()
#13 /home/mysite/public_html/application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
#14 /home/mysite/public_html/application/index.php(214): Engine_Application->run()
#15 /home/mysite/public_html/index.php(24): include('/home/mysite...')
#16 {main}
```

What versions of software are you using?
----------------------------------------
**Operating System: CentOS 6.8 64bit / Cpanel
PHP Version 5.6.20 - PHP Handler FCGI
Zend Engine v2.6.0
MySQL 5.6

**SocialEngine PHP Version: 4.8.11

**Comment by Khushboo016** [comment]
Hi @crazytechjunkie , We are not able to reproduce this issue on our local setup, so it seems to be related to your specific installation and so, we suggest you to open a support ticket for this at https://www.socialengine.com/client/ticket/create or you can also email us at support@socialengine.com.

Thanks!

**Comment by Elshara** [comment]
Cannot reproduce this either.

**Comment by crazytechjunkie** [comment]
I found the problem... I had ZEND Loader 7 complied once I recompiled without the loader it worked correctly. Thanks for the feedback.
