### ISSUE TITLE
Photo User Tagging Creating Posts on Newsfeed With No Associated Text

### ISSUE THREAD

**Issue by jonathanbloom** [SocialEngine/phpv4-issues#8]
Tagged users in photos. Shows picture in main feed with no text indicating why it is showing the pictures.

```
2015-02-18T15:39:16+00:00 WARN (4): [2] preg_replace(): Parameter mismatch, pattern is a string while replacement is an array (/home/USERNAME/public_html/application/modules/Activity/Api/Core.php) [69]
Error Code: 1b37ef
Stack trace:
#0 /home/USERNAME/public_html/application/modules/Activity/Api/Core.php(69): preg_replace('/\{var\:\$label\}/', Array, 'assemble('{item:$subject} tagged {item:$ob...', Array)
#2 /home/USERNAME/public_html/application/modules/Activity/views/scripts/_activityText.tpl(105): Activity_Model_Action->getContent()
#3 /home/USERNAME/public_html/application/libraries/Zend/View.php(108): include('/home/USERNAME/public_html/applic...')
#4 /home/USERNAME/public_html/application/libraries/Zend/View/Abstract.php(890): Zend_View->_run('/home/USERNAME/public_html/applic...')
#5 /home/USERNAME/public_html/application/libraries/Zend/View/Helper/Partial.php(109): Zend_View_Abstract->render('_activityText.tpl')
#6 (unknown file)(0): Zend_View_Helper_Partial->partial('_activityText.tpl', 'activity', Array)
#7 /home/USERNAME/public_html/application/libraries/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)
#8 /home/USERNAME/public_html/application/modules/Activity/View/Helper/ActivityLoop.php(65): Zend_View_Abstract->__call('partial', Array)
#9 /home/USERNAME/public_html/application/modules/Activity/View/Helper/ActivityLoop.php(65): Zend_View->partial('_activityText.tpl', 'activity', Array)
#10 (unknown file)(0): Activity_View_Helper_ActivityLoop->activityLoop(Array, Array)
#11 /home/USERNAME/public_html/application/libraries/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)
#12 /home/USERNAME/public_html/application/modules/Activity/widgets/feed/index.tpl(72): Zend_View_Abstract->__call('activityLoop', Array)
#13 /home/USERNAME/public_html/application/modules/Activity/widgets/feed/index.tpl(72): Zend_View->activityLoop(Array, Array)
#14 /home/USERNAME/public_html/application/libraries/Zend/View.php(108): include('/home/USERNAME/public_html/applic...')
#15 /home/USERNAME/public_html/application/libraries/Zend/View/Abstract.php(890): Zend_View->_run('/home/USERNAME/public_html/applic...')
#16 /home/USERNAME/public_html/application/libraries/Engine/Content/Widget/Abstract.php(292): Zend_View_Abstract->render('application/modules/Activity/wid...')
#17 /home/USERNAME/public_html/application/libraries/Engine/Content/Widget/Abstract.php(258): Engine_Content_Widget_Abstract->renderScript()
#18 /home/USERNAME/public_html/application/libraries/Engine/Content/Element/Widget.php(73): Engine_Content_Widget_Abstract->render()
#19 /home/USERNAME/public_html/application/libraries/Engine/Content/Element/Abstract.php(583): Engine_Content_Element_Widget->_render()
#20 /home/USERNAME/public_html/application/libraries/Engine/Content/Decorator/Children.php(31): Engine_Content_Element_Abstract->render()
#21 /home/USERNAME/public_html/application/libraries/Engine/Content/Element/Abstract.php(594): Engine_Content_Decorator_Children->render('')
#22 /home/USERNAME/public_html/application/modules/Core/controllers/WidgetController.php(60): Engine_Content_Element_Abstract->render()
#23 /home/USERNAME/public_html/application/libraries/Zend/Controller/Action.php(516): Core_WidgetController->indexAction()
#24 /home/USERNAME/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#25 /home/USERNAME/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Zend_Controller_Request_Http, Zend_Controller_Response_Http)
#26 /home/USERNAME/public_html/application/modules/Core/Bootstrap.php(80): Zend_Controller_Front->dispatch()
#27 /home/USERNAME/public_html/application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
#28 /home/USERNAME/public_html/application/index.php(205): Engine_Application->run()
#29 /home/USERNAME/public_html/index.php(24): include('/home/USERNAME/public_html/applic...')
#30 {main}
```

**Comment by shivani2910** [comment]
Hi @jonathanbloom, 

This is not a known issue in our default SocialEngine modules. Please open a support ticket along with the details of your website and steps to reproduce this problem to enable us look into this issue in your SocialEngine installation. 

We appreciate your support and cooperation.

Best Regards,
Shivani

**Comment by arundevr** [comment]
How to resolve this issue?
